### ISSUE TITLE
Package is missing dist.zip

### ISSUE THREAD

**Issue by matejdro** [a2/pebble-activity-indicator-layer#3]
Not sure if I'm doing something wrong, but your package seems to be missing `dist.zip`. Only `package.json` and `README.md` get downloaded.

**Comment by matejdro** [comment]
Note: Version `1.0.0` seems to work fine.

**Comment by a2** [comment]
Try with version 1.0.2? I ran `pebble package publish` this time instead of `npm publish`. Maybe that helps?

**Comment by matejdro** [comment]
Same issue with 1.0.2.

**Comment by a2** [comment]
Interesting. I have no idea what I'm doing wrong then. Is there any good documentation on how to do this correctly? 😅

**Comment by matejdro** [comment]
Sorry, I know even less about those things. Maybe try Pebble's slack channel?

**Comment by matejdro** [comment]
I've been doing some tests and solution is actually pretty simple: before you do `pebble package publish`, you must do `pebble build` first 😄

**Comment by matejdro** [comment]
@a2 Now that we know what is wrong, could you push working build for Diorite out?

I would really prefer not to just copy paste the library into the code and fix it myself, because I like giving you the credit for your work by including your work explicitly via package manager.

**Comment by a2** [comment]
@matejdro I don't have the Pebble toolchain on this machine right now so it may take a few hours. But I'll try to get it done today!

**Comment by a2** [comment]
@matejdro Try it now. I think it works?

**Comment by matejdro** [comment]
Yes! `1.0.3` finally works and builds for Diorite. Thanks!
